### ISSUE TITLE
代码在odoo12版本中不能跑。

### ISSUE THREAD

**Issue by fu1996** [ScottAI/-Odoo---#4]
作者
您好，我买了您的教材，我用的版本是12的，即使从您这里下载的代码，直接拷贝过去还是一样的不能跑。如果您有空的话麻烦您告知一下。谢谢

![482XZMXU_{ S8% 1SBES3IJ](https://user-images.githubusercontent.com/42232973/62116901-921edc00-b2ed-11e9-9f6d-df4d449437fc.png)

**Comment by lgwMichael** [comment]
同问

**Comment by beibeiaiwuhao** [comment]
同问，实战项目按着操作，问题不断，感觉实战项目不能很清晰的梳理项目的结构

**Comment by fu1996** [comment]
give up
